# Backend https://www.netlifycms.org/docs/configuration-options/#backend
backend:
  name: git-gateway
  branch: master

# Publish mode https://www.netlifycms.org/docs/configuration-options/#publish-mode
# publish_mode: editorial_workflow

# Media and Public Folders https://www.netlifycms.org/docs/configuration-options/#media-and-public-folders
media_folder: 'app/static/images/uploads' # Media files will be stored in the repo under images/uploads
public_folder: '/images/uploads'

# URL to the published site
site_url: https://silly-bombolone-eb69bf.netlify.app

# The CMS UI will include a link in the fixed area at the top of the page with this URL
display_url: https://silly-bombolone-eb69bf.netlify.app

# Brands the CMS with our logo
logo_url: https://imgur.com/2LBZtL8.png

# Collections https://www.netlifycms.org/docs/configuration-options/#collections
collections:
  - label: Settings
    name: settings
    files:
      - label: General
        name: general
        format: json
        file: 'app/content/settings/general.json'
        fields:
          - { label: Title, name: title, widget: string }
          - { label: 'Title Template', name: titleTemplate, widget: string }
          - { label: Logo, name: logo, widget: image }
          - { label: Icon, name: icon, widget: image }
          - { label: 'Loading Color', name: loadingColor, widget: string, default: '#000000' }
          - { label: 'SEO Description', name: seoDescription, widget: text, required: false }
          - { label: 'SEO Meta Image', name: seoMetaImage, widget: image, required: false }
      - label: Manifest
        name: manifest
        format: json
        file: 'app/content/settings/manifest.json'
        fields:
          - { label: Name, name: name, widget: string }
          - { label: 'Short name', name: shortName, widget: string }
          - { label: Description, name: description, widget: text }
          - { label: Lang, name: lang, widget: string, default: en }
  - name: 'portfolio'
    label: 'Portfolio'
    folder: 'app/content/portfolio'
    create: true
    format: 'json'
    fields:
      - { label: 'Piece', name: featuredImage, widget: image }
      - { label: Name, name: title, widget: string }
      - { label: 'Social media link', name: socialMediaLink, widget: string }
  - name: 'staff'
    label: 'Staff'
    folder: 'app/content/staff'
    create: true
    format: 'json'
    sort: 'position:asc'
    fields:
      - { label: 'Image', name: featuredImage, widget: image }
      - { label: Name, name: title, widget: string }
      - { label: Role, name: role, widget: string }
      - { label: Bio, name: bio, widget: string }
      - label: 'External Links'
        name: externalLinks
        widget: list
        max: 5
        label_singular: 'external link'
        fields:
          - {
              label: 'Site name (e.g. Instagram, DeviantArt, Website)',
              name: 'name',
              widget: 'string',
            }
          - { label: 'Link / URL', name: 'url', widget: string }
      - label: 'Position in page'
        name: 'position'
        hint: 'Optional number to order the staff member in the Team page.'
        widget: 'number'
        required: false
        value_type: 'int'
        min: 1
        step: 1
  - name: 'artist'
    label: 'Artists'
    folder: 'app/content/artists'
    create: true
    format: 'json'
    sort: 'position:asc'
    fields:
      - { label: 'Image', name: featuredImage, widget: image }
      - { label: Nombre, name: title, widget: string }
      - { label: Bio, name: bio, widget: string }
      - label: 'External Links'
        name: externalLinks
        widget: list
        max: 5
        label_singular: 'external link'
        fields:
          - {
              label: 'Site name (e.g. Instagram, DeviantArt, Website)',
              name: 'name',
              widget: 'string',
            }
          - { label: 'Link / URL', name: 'url', widget: 'string' }
      - label: 'Position in page'
        name: 'position'
        hint: 'Optional number to order the artist in the Team page.'
        widget: 'number'
        required: false
        value_type: 'int'
        min: 1
        step: 1
  - name: 'monthlyShowcase'
    label: 'Monthly Showcase'
    files:
      - label: 'OTMs'
        name: 'otms'
        file: 'app/content/monthly_showcase/otms.json'
        fields:
          - label: 'Artist of the month'
            name: 'artistOfTheMonth'
            widget: 'object'
            summary: '{{fields.name}}'
            fields:
              - { label: "Artist's name", name: 'artistName', widget: string }
              - { label: 'Social media link', name: socialMediaLink, widget: string }
              - { label: 'Social media handler', name: socialMediaHandler, widget: string }
              - label: 'Pieces'
                name: pieces
                widget: list
                max: 5
                label_singular: 'piece'
                fields:
                  - {
                      label: 'Image',
                      name: 'featuredImage',
                      widget: 'image',
                    }
          - label: 'Piece of the month'
            name: 'pieceOfTheMonth'
            widget: 'object'
            summary: '{{fields.name}}'
            fields:
              - { label: "Artist's name", name: 'artistName', widget: string }
              - { label: "Pet's name", name: 'petName', widget: 'string' }
              - { label: 'Social media link', name: socialMediaLink, widget: string }
              - { label: 'Social media handler', name: socialMediaHandler, widget: string }
              - { label: 'Piece', name: featuredImage, widget: image }
          - label: "Staff's highlight"
            name: 'staffHighlight'
            widget: 'object'
            summary: '{{fields.name}}'
            fields:
              - { label: "Artist's name", name: 'artistName', widget: string }
              - { label: "Pet's name", name: 'petName', widget: 'string' }
              - { label: 'Social media link', name: socialMediaLink, widget: string }
              - { label: 'Social media handler', name: socialMediaHandler, widget: string }
              - { label: 'Piece', name: featuredImage, widget: image }
          - label: 'Mentor of the month'
            name: 'mentorOfTheMonth'
            widget: 'object'
            summary: '{{fields.name}}'
            fields:
              - { label: "Artist's name", name: 'artistName', widget: string }
              - { label: 'Social media link', name: socialMediaLink, widget: string }
              - { label: 'Social media handler', name: socialMediaHandler, widget: string }
              - { label: 'Piece', name: featuredImage, widget: image }
